export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST";
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS";
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE";

export const EMAIL_LOGIN_REQUEST = "EMAIL_LOGIN_REQUEST";
export const EMAIL_LOGIN_SUCCESS = "EMAIL_LOGIN_SUCCESS";
export const EMAIL_LOGIN_FAILURE = "EMAIL_LOGIN_FAILURE";

export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";

//Cart and Wishlist Functionality
export const REQUEST_MODIFY_ITEM_QUANTITY = "REQUEST_MODIFY_ITEM_QUANTITY";
export const SUCCESS_MODIFY_ITEM_QUANTITY = "SUCCESS_MODIFY_ITEM_QUANTITY";
export const FAILURE_MODIFY_ITEM_QUANTITY = "FAILURE_MODIFY_ITEM_QUANTITY";


export const REQUEST_ADD_CART = "REQUEST_ADD_CART";
export const SUCCESS_ADD_CART = "SUCCESS_ADD_CART";
export const FAILURE_ADD_CART = "FAILURE_ADD_CART";

export const REQUEST_REMOVE_CART = "REQUEST_REMOVE_CART";
export const SUCCESS_REMOVE_CART = "SUCCESS_REMOVE_CART";
export const FAILURE_REMOVE_CART = "FAILURE_REMOVE_CART";

export const REQUEST_EMPTY_CART = "REQUEST_EMPTY_CART";
export const SUCCESS_EMPTY_CART = "SUCCESS_EMPTY_CART";
export const FAILURE_EMPTY_CART = "FAILURE_EMPTY_CART";


export const REQUEST_UPDATE_ADDRESS = "REQUEST_UPDATE_ADDRESS";
export const SUCCESS_UPDATE_ADDRESS = "SUCCESS_UPDATE_ADDRESS";
export const FAILURE_UPDATE_ADDRESS = "FAILURE_UPDATE_ADDRESS";