export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST";
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS";
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE";


export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";


export const REQUEST_UPDATE_ADDRESS = "REQUEST_UPDATE_ADDRESS";
export const SUCCESS_UPDATE_ADDRESS = "SUCCESS_UPDATE_ADDRESS";
export const FAILURE_UPDATE_ADDRESS = "FAILURE_UPDATE_ADDRESS";