export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"   
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"   
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"

export const GET_SINGLE_PRODUCTS_REQUEST="GET_SINGLE_PRODUCTS_REQUEST"   
export const GET_SINGLE_PRODUCTS_SUCCESS="GET_SINGLE_PRODUCTS_SUCCESS"   
export const GET_SINGLE_PRODUCTS_FAILURE="GET_SINGLE_PRODUCTS_FAILURE"

export const ADD_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const ADD_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const ADD_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"


//Cart and Wishlist Functionality
export const REQUEST_MODIFY_ITEM_QUANTITY = "REQUEST_MODIFY_ITEM_QUANTITY";
export const SUCCESS_MODIFY_ITEM_QUANTITY = "SUCCESS_MODIFY_ITEM_QUANTITY";
export const FAILURE_MODIFY_ITEM_QUANTITY = "FAILURE_MODIFY_ITEM_QUANTITY";


export const REQUEST_ADD_CART = "REQUEST_ADD_CART";
export const SUCCESS_ADD_CART = "SUCCESS_ADD_CART";
export const FAILURE_ADD_CART = "FAILURE_ADD_CART";

export const REQUEST_REMOVE_CART = "REQUEST_REMOVE_CART";
export const SUCCESS_REMOVE_CART = "SUCCESS_REMOVE_CART";
export const FAILURE_REMOVE_CART = "FAILURE_REMOVE_CART";

export const REQUEST_EMPTY_CART = "REQUEST_EMPTY_CART";
export const SUCCESS_EMPTY_CART = "SUCCESS_EMPTY_CART";
export const FAILURE_EMPTY_CART = "FAILURE_EMPTY_CART";


export const REQUEST_UPDATE_ADDRESS = "REQUEST_UPDATE_ADDRESS";
export const SUCCESS_UPDATE_ADDRESS = "SUCCESS_UPDATE_ADDRESS";
export const FAILURE_UPDATE_ADDRESS = "FAILURE_UPDATE_ADDRESS";