export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"   
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"   
export const GET_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"

export const GET_SINGLE_PRODUCTS_REQUEST="GET_SINGLE_PRODUCTS_REQUEST"   
export const GET_SINGLE_PRODUCTS_SUCCESS="GET_SINGLE_PRODUCTS_SUCCESS"   
export const GET_SINGLE_PRODUCTS_FAILURE="GET_SINGLE_PRODUCTS_FAILURE"

//Reviews 
export const GET_REVIEWS_REQUEST="GET_REVIEWS_REQUEST"   
export const GET_REVIEWS_SUCCESS="GET_REVIEWS_SUCCESS"   
export const GET_REVIEWS_FAILURE="GET_REVIEWS_FAILURE"

export const ADD_REVIEWS_REQUEST="ADD_REVIEWS_REQUEST"
export const ADD_REVIEWS_SUCCESS="ADD_REVIEWS_SUCCESS"
export const ADD_REVIEWS_FAILURE="ADD_REVIEWS_FAILURE"

export const UPDATE_REVIEWS_REQUEST="UPDATE_REVIEWS_REQUEST"
export const UPDATE_REVIEWS_SUCCESS="UPDATE_REVIEWS_SUCCESS"
export const UPDATE_REVIEWS_FAILURE="UPDATE_REVIEWS_FAILURE"


//Question
export const GET_QUESTION_REQUEST="GET_QUESTION_REQUEST"   
export const GET_QUESTION_SUCCESS="GET_QUESTION_SUCCESS"   
export const GET_QUESTION_FAILURE="GET_QUESTION_FAILURE"

export const ADD_QUESTION_REQUEST="ADD_QUESTION_REQUEST"
export const ADD_QUESTION_SUCCESS="ADD_QUESTION_SUCCESS"
export const ADD_QUESTION_FAILURE="ADD_QUESTION_FAILURE"

//Cart Functionality
export const REQUEST_MODIFY_ITEM_QUANTITY = "REQUEST_MODIFY_ITEM_QUANTITY";
export const SUCCESS_MODIFY_ITEM_QUANTITY = "SUCCESS_MODIFY_ITEM_QUANTITY";
export const FAILURE_MODIFY_ITEM_QUANTITY = "FAILURE_MODIFY_ITEM_QUANTITY";

export const REQUEST_ADD_CART = "REQUEST_ADD_CART";
export const SUCCESS_ADD_CART = "SUCCESS_ADD_CART";
export const FAILURE_ADD_CART = "FAILURE_ADD_CART";

export const REQUEST_REMOVE_CART = "REQUEST_REMOVE_CART";
export const SUCCESS_REMOVE_CART = "SUCCESS_REMOVE_CART";
export const FAILURE_REMOVE_CART = "FAILURE_REMOVE_CART";

export const REQUEST_EMPTY_CART = "REQUEST_EMPTY_CART";
export const SUCCESS_EMPTY_CART = "SUCCESS_EMPTY_CART";
export const FAILURE_EMPTY_CART = "FAILURE_EMPTY_CART";

// Wishlist Functionality
export const REQUEST_ADD_WISHLIST = "REQUEST_ADD_WISHLIST";
export const SUCCESS_ADD_WISHLIST = "SUCCESS_ADD_WISHLIST";
export const FAILURE_ADD_WISHLIST = "FAILURE_ADD_WISHLIST";

export const REQUEST_REMOVE_WISHLIST = "REQUEST_REMOVE_WISHLIST";
export const SUCCESS_REMOVE_WISHLIST = "SUCCESS_REMOVE_WISHLIST";
export const FAILURE_REMOVE_WISHLIST = "FAILURE_REMOVE_WISHLIST";

export const REQUEST_EMPTY_WISHLIST = "REQUEST_EMPTY_WISHLIST";
export const SUCCESS_EMPTY_WISHLIST = "SUCCESS_EMPTY_WISHLIST";
export const FAILURE_EMPTY_WISHLIST = "FAILURE_EMPTY_WISHLIST";

// Admin

export const ADD_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST"
export const ADD_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"
export const ADD_PRODUCTS_FAILURE="GET_PRODUCTS_FAILURE"

export const ANSWER_QUESTION_REQUEST="ANSWER_QUESTION_REQUEST"
export const ANSWER_QUESTION_SUCCESS="ANSWER_QUESTION_SUCCESS"
export const ANSWER_QUESTION_FAILURE="ANSWER_QUESTION_FAILURE"